Guzzing/Studay_Client

.github/workflows/CodeDeploy.yml

스터데이 클라이언트 배포를 위한 워크플로우입니다.
- 현재는 S3 업로드 까지만 구현을 했습니다.

feat: 스터데이 S3 배포 워크플로우 생성

---

.eslintrc.cjs
.storybook/preview.ts
package.json
src/components/common/Modal/InputModal.tsx
src/components/common/Modal/Modal.stories.tsx
src/components/common/Modal/Modal.tsx
src/hooks/useModal.tsx
tailwind.config.js

Modal 컴포넌트를 구현하였습니다.
- 모달 컴포넌트 구현
- InputModal 구현
- 모달 커스텀 훅 구현
- 허스키문제가 있어 src/ 하위의 js,ts만 린트검사하도록 수정하였습니다.
- 스토리북 테일윈드가 적용되지 않는 문제가 있어 스토리북 설정파일 수정하였습니다.
- 테일윈드 설정파일에서 blue-500이 두개가 존재해 변경해 주었습니다.
close #8

feat: Modal 컴포넌트구현

---

src/components/common/stepquestion/StepQuestion.stories.tsx
src/components/common/stepquestion/StepQuestion.tsx
src/components/common/stepquestion/StepQuestionType.ts
src/components/common/stepquestion/constants.ts

StepQuestion 컴포넌트 구현 하였습니다.
StepQuestion 컴포넌트를 구현 하였습니다. Step, Text를 받아서 넘버링과 텍스트를 보여줌니다.
- 텍스트 스타일이 현재 와이어 프레임과 다른 문제가 있어 지성님이 공통 스타일 변경해주시면 다시 적용해서 업로드 하겠습니다.
close #11

feat: StepQuestion 컴포넌트 구현

---

src/components/common/navigationbar/NavigationBar.stories.tsx
src/components/common/navigationbar/NavigationBar.tsx
src/components/common/navigationbar/NavigationBarType.ts
src/components/common/navigationbar/constants.ts
src/styles/index.css

네비게이션을 구현 하였습니다.
네비게이션 컴포넌트를 구현 하였습니다.
close #13

feat: 네비게이션 구현

---

src/components/common/informationBox/Information.stories.tsx
src/components/common/informationBox/InformationBox.tsx
src/components/common/informationBox/InformationBoxType.ts

Information 컴포넌트 개발 
<h2>InformationBox props설명</h2>
<li>image : 처음 아무것도 설정하지 않았을 때를 대비해 default parameter로 우선 임의의 profile넣어뒀습니다.</li>
<li>mainTitle: 자식의 이름을 넣어두는 곳</li>
<li>subTitle: 자식의 학년을 넣어두는 곳</li>
<li>description: 한 줄 정도의 간단한 설명을 넣어두는 곳입니다.</li>
- description이 넘쳤을 떄의 css를 만들어놨지만 글자수를 설정해놓는게 좋을 것 같은데 어떻게 생각하시는지 궁금합니다.
close #43

informationBox 컴포넌트 개발

---

src/components/common/header/Header.tsx
src/components/common/informationBox/InformationBox.tsx
src/components/common/listRow/ListRow.tsx
src/components/common/navigationbar/NavigationBar.tsx
src/components/common/navigationbar/constants.ts
src/components/common/profile/Profile.tsx
src/components/common/profile/ProfileType.ts
src/pages/EditChildren/EditChildren.tsx
src/pages/home/HomePage.tsx
src/routes/index.tsx

아이의 정보를 수정할 수 있는 api를 구현했습니다.
실제로 수정 버튼을 눌렀을 때 나타나는 화면 view를 구성하고 api로 연결하는 작업은 
백엔드 작업이 완료되면 추가해 넣도록 하겠습니다. 
현재 버튼 크기가 피그마에 설정 된 부분보다 큰데, 이는 높이 때문이므로 지성님께서 수정해주신 PR 머지해서 추후 자동으로 수정될 예정입니다. 
close #68

feat: 아이 정보 보기, 수정하기 페이지 구현 

---

src/App.tsx
src/components/common/header/Header.tsx
src/components/common/informationBox/InformationBox.tsx
src/components/common/inputbox/input/Input.tsx
src/components/common/inputbox/select/Select.tsx
src/components/common/inputbox/select/SelectType.ts
src/components/common/scheduleBox/ScheduleBox.tsx

만들었던 컴포넌트들의 폰트 클래스를 최신 dev브랜치를 반영하여 업데이트 했습니다.
<h2>폰트 class 업데이트, Select컴포넌트 value기본 세팅</h2>
<li>1. 최신 font class를 제대로 반영하고있는지</li>
<li>2. selectbox의 value가 잘 변경이 되는지 확인 부탁드립니다.</li>
close #65

컴포넌트 className 업데이트

---

src/api/index.ts

feat: API 공통 파일 구현

---

src/components/layout/Layout.tsx
src/routes/index.tsx
src/styles/index.css

글로벌 높이를 수정하였습니다.
- #root 높이 제거
- 높이 자동 계산
close #75

feat: 글로벌 높이 수정

---

src/components/common/navigationbar/NavigationBar.tsx

학원지도, 홈 클릭시 이동되도록 수정
if문으로 구현해서 조금 코드가 더럽습니다. 데모 이후 작업이 필요할거 같습니다.

feat: 네비게이션 수정

---

.github/workflows/CodeDeploy.yml

깃 배포를 위한 워크플로우를 수정하였습니다.
.env 파일을 만듬니다.

feat: 깃 액션 워크 플로우 수정

---

src/libs/api/autorization/LoginApi.ts
src/pages/login/LoginPage.tsx

feat: 로그인 리다이렉트 url수정

---

src/libs/api/autorization/LoginApi.ts
src/pages/login/LoginPage.tsx

* feat: 로그인 리다이렉트 url수정
* feat: 로그인 리다이렉트 url수정
close #이슈번호

feat: 로그인 리다이렉트 url수정 (#97)

---

src/libs/api/autorization/LoginApi.ts
src/pages/login/LoginPage.tsx

* feat: 로그인 리다이렉트 url수정
* feat: 로그인 리다이렉트 url수정
* feat: 로그인 리다이렉트 url수정
* feat: 로그인 리다이렉트 url수정
---------
close #이슈번호

fix: www 도메인 제거

---

src/libs/api/index.ts

fix: 초기 토큰 삭제(interceptor에서 처리)

---

src/libs/api/autorization/LoginApi.ts

feat: redirect uri다시 수정

---

src/libs/api/autorization/LoginApi.ts
src/pages/home/HomePage.tsx
src/pages/login/LoginPage.tsx

feat: 인가코드를 받아온 후 로그인 api요청 코드 HomePage로 이동

---

src/components/BottomSheet/BottomSheetContent.tsx
src/components/common/bottomsheet/BottomSheet.tsx
src/components/common/inputbox/select/Select.tsx
src/components/common/inputbox/select/SelectType.ts
src/components/common/textBox/TextBox.stories.tsx
src/components/common/textBox/TextBox.tsx
src/components/common/textBox/TextBoxType.ts
src/components/map/NaverMap.tsx
src/components/selectcity/SelectCityStep.tsx
src/components/selectcity/SelectCityStep1.tsx
src/components/selectcity/SelectCityStep2.tsx
src/components/selectcity/SelectCityStep3.tsx
src/libs/api/mapapi/mapApi.ts
src/libs/api/mapapi/mapApiType.ts
src/libs/store/mapInfoAtom.ts
src/libs/utils/throttle.ts
src/pages/map/MapPage.tsx
src/pages/selectcity/SelectCity.tsx
src/types/mapPage.ts
src/types/selectcity.ts

selectcity 페이지 리펙토링 및 리엑트 쿼리 마이그레이션을 같이 진행하였습니다.
- 리엑트 쿼리 적용
- selectcity 마이그레이션
- selectcity 조타이 적용
- selectcity 을 합성컴포넌트 (퍼널)을 적용하였습니다.
- SelectCityStep 1, 2, 3을 한개로 만들지 여러개로 만들지 고민이 되네요
close #102

refact : selectcity 리엑트 쿼리 적용 및 리펙토링

---

src/components/academy/SelectMyChlid.tsx
src/components/common/inputbox/input/Input.tsx
src/components/common/inputbox/select/Select.tsx
src/components/common/label/LabelType.ts
src/components/common/scheduleBox/ScheduleBox.tsx
src/components/common/scheduleBox/ScheduleBoxType.ts
src/components/selectcity/SelectCityStep2.tsx
src/libs/api/academy/AcademyApi.ts
src/libs/api/academy/AcademyType.ts
src/libs/api/dashboard/DashBoardApi.ts
src/libs/api/dashboard/DashBoardType.ts
src/libs/store/academyInfo.tsx
src/libs/utils/dateParse.ts
src/libs/utils/weekParse.ts
src/pages/academy/AcademyDashboard.tsx
src/pages/academy/AcademyDetail.tsx
src/pages/academy/AddSchedule/AddAcademyInfo.tsx
src/pages/academy/AddSchedule/AddPayment.tsx
src/routes/index.tsx

Dashboard 상세보기, toggle On, off 구현을 하였습니다. 
close #130

[Feat]: dashboard 상세보기 뷰 구현

---

.eslintrc.cjs
src/components/academy/CustomTimePicker.tsx
src/components/academy/SelectTime.tsx
src/components/common/listRowSelect/ListRowSelect.tsx
src/components/common/navigationbar/NavigationBar.tsx
src/components/dashboard/SelectChild.tsx
src/components/dashboard/SelectLesson.tsx
src/libs/api/academy/AcademyApi.ts
src/libs/api/children/ChildrenApi.ts
src/libs/api/dashboard/DashBoardType.ts
src/pages/academy/AcademyDashboard.tsx
src/pages/academy/AddSchedule/AddAcademyInfo.tsx
src/pages/academy/AddSchedule/AddAcademyName.tsx
src/pages/academy/AddSchedule/AddPayment.tsx
src/pages/academy/AddSchedule/AddSchedule.tsx
src/pages/academy/AddSchedule/index.tsx
src/pages/academy/academyDetail/AcademyDetailHeader.tsx
src/pages/academy/academyDetail/index.tsx
src/pages/academy/editAcademy/index.tsx
src/pages/home/HomePage.tsx
src/routes/index.tsx

학원 정보를 수정할 수 있는 api를 돌아갈 수 있게끔 만들어놨습니다. 
(스케쥴, 아이정보, 반은 못바꿔용~) 
아직 몇가지 버벅임 이슈가 있는데, 이는 리팩토링 시 추후 개선하도록 하겠습니다! 감사합니다.
close #169

[Feat]: 학원 정보 수정 

---

src/libs/api/mypage/myPageType.ts
src/pages/EditChildren/EditingChildren.tsx
src/pages/mypage/MyPage.tsx

/edit/{childId}랜더링 문제 확인해주시면 감사하겠습니다!

/edit/{childId}랜더링 문제

---

.eslintrc.cjs
package-lock.json
package.json
src/components/common/toast/index.tsx
src/components/review/ReviewBottomSheet.tsx
src/libs/api/review/reviewApi.ts
src/libs/api/review/reviewType.ts
src/libs/hooks/useToastify.ts
src/pages/academy/AcademyDashboard.tsx
src/pages/academy/AddSchedule/AddPayment.tsx
src/pages/academy/academyDetail/AcademyDetailHeader.tsx
src/pages/academy/academyDetail/AcademySetting.tsx

학원에 리뷰를 남길 수 있도록 바텀시트 모달창을 열어주었습니다. 
close #171

[Feat]: 학원 정보 리뷰 남기기

---

src/components/common/inputbox/select/Select.tsx
src/components/common/inputbox/select/SelectType.ts
src/components/dashboard/SelectChild.tsx
src/components/schedule/SelectAttendanceDate.tsx
src/libs/api/schedule/scheduleApi.ts
src/libs/api/schedule/scheduleType.ts
src/libs/store/scheduleInfo.tsx
src/pages/schedule/new/AddScheduleAcademy.tsx
src/pages/schedule/new/AddScheduleMemo.tsx
src/pages/schedule/new/AddScheduleTime.tsx
src/pages/schedule/new/index.tsx
src/routes/index.tsx

학원 정보를 불러와 스케쥴을 생성할 수 있는 화면을 만들었습니다. 
close #159

[Feat]: 스케쥴 생성하기 기능 

---

src/components/common/icon/Icon.tsx
src/libs/api/schedule/scheduleApi.ts
src/libs/api/schedule/scheduleType.ts

icon 수정 및 컨플릿 에러 수정 하였습니다.
Icon에 넣었던 이벤트 전파 방지 코드를 제거하고
컨플릿을 해결하면서 잘 수정이 안된 코드를 수정하였습니다.

hotfix: icon 수정 및 컨플릿 에러 수정

---

src/components/common/scheduleProfileBox/ScheduleProfileBox.tsx
src/components/schedule/scheduleModal/ScheduleModal.tsx
src/libs/api/schedule/scheduleType.ts
src/libs/utils/date.ts
src/pages/schedule/Schedule.tsx

스케줄 페이지 수정 
1. Icon에 적용된 이벤트 전파방지 코드를 상위 div에서 적용하도록 수정하였습니다.
2. 백엔드 API에서 endTime => entTIme로 주고 있어서 수정하였습니다.
3. 디테일 페이지 이동 URL을 수정하였습니다.

hotfix: 디테일 페이지 이동 및 이벤트 전파방지 추가

---

src/components/selectcity/CityStep.tsx

SelectRef 추가 (이전 스텝으로 이동시 Select 컴포넌트가 초기화 되지 않는 문제)
SelectRef 추가 후 useEffect에서 스텝이 변경될때 마다 index를 0으로 주도록 수정하였습니다.

hotfix: SelectRef 추가 (이전 스텝으로 이동시 Select 컴포넌트가 초기화 되지 않는 문제)

---

package-lock.json
src/components/common/progressBar/ProgressBar.stories.tsx
src/components/common/progressBar/ProgressBar.tsx
src/components/common/slider/Slider.stories.tsx
src/components/common/slider/Slider.tsx
src/pages/onboarding/OnbardingPage.tsx
src/pages/schedule/new/index.tsx

온보딩 과정에서 progress bar를 활용할 수 있도록 합쳐 놨습니다.
희석님께서 슬라이더 바도 바로 사용할 수 있게끔 UI 조금 더 다듬어 전달드리겠습니다. 
-close #86

[Feat]: 온보딩 progress Bar 작업 

---

src/libs/api/mypage/myPageApi.ts

마이페이지 api요청 수정

---

src/libs/store/likeacademyAtom.tsx
src/pages/likeAcademy/LikeAcademy.tsx

fix: 마운트시 나타나는 데이터 제거

---

src/libs/store/likeacademyAtom.tsx
src/pages/likeAcademy/LikeAcademy.tsx
src/pages/setting/SettingPage.tsx

<li>1. setting page 생성(안 되어있었음)</li>
<li>2. deleteApi 미반영 문제</li>
<h2>likeAcademy page</h2>
<h2>세팅 페이지</h2>
https://github.com/Guzzing/Studay_Client/assets/85999976/a1afe830-ab84-4725-8d21-2f72807a41e3
close #207

likeAcademy 버그 수정

---

src/App.tsx
src/components/common/header/Header.tsx
src/components/common/toast/index.tsx
src/components/layout/Layout.tsx
src/components/review/ReviewBottomSheet.tsx
src/libs/api/index.ts
src/pages/academy/AcademyDashboard.tsx
src/pages/academy/academyDetail/AcademySetting.tsx
src/pages/academy/addSchedule/index.tsx
src/pages/academy/editAcademy/index.tsx
src/pages/home/HomePage.tsx
src/pages/mypage/MyPage.tsx
src/pages/onboarding/OnbardingPage.tsx
src/pages/schedule/new/index.tsx

이제 alert 창을 대체할 수 있는 Toast UI 가 생성되어 이를 이용해주시면 됩니다.
사용 방법을 간단히 안내드리겠습니다.
```ts
const { setToast } = useToastify()
```
이렇게 상단부에 커스텀훅 호출하시고, `alert` 창을 사용하고 싶은 부분에 아래 코드를 작성해주세요.
```ts
setToast({ comment: '리뷰는 4개 이상 남길 수 없어요.', type: 'warning' })
```
`comment`에는 넣고 싶은 문자열을 넣고, `type`은 총 네가지예요.
`warning`, `info`, `success`, `error` 이렇게있습니다. 
close #180

[Feat] : Toast UI 생성

---

src/pages/home/HomePage.tsx

fix: homepage bug해결

---

src/libs/api/mypage/myPageApi.ts
src/pages/mypage/MyPage.tsx

마이 페이지에서 불필요한 useEffect, state를 제외하고, useQuery를 적용하였습니다 
close #242

fix: 마이페이지 리액트 쿼리 적용

---

src/components/common/navigationbar/NavigationBar.tsx
src/styles/index.css

fix: 네비게이션바를 선택 했을때 이동이 안되는 문제 수정

---

src/pages/home/HomePage.tsx

넘치지 않을때도 overflow가 되는 문제 해결해서, 넘칠 때만 overflow되게 설정했습니다
close #252

fix: homepage scroll error해결

---

src/components/common/slider/Slider.stories.tsx
src/components/common/slider/Slider.tsx
src/libs/store/mapFilterAtom.ts
src/pages/filter/FilterPage.tsx

hotfix: 필터 구현

---

src/pages/mypage/MyPage.tsx

마이페이지 pull 에러 수정 

---

src/pages/login/LoginPage.tsx
src/pages/mypage/MyPage.tsx

로그인 깜빡깜빡 버그 해결

---

src/pages/map/MapPage.tsx

셋팅 페이지 로직 추가로 인해 지도가 보이지 않는 문제를 수정 하였습니다.
div 제거

fix: 맵 페이지가 보이지 않는 문제 수정

---

src/pages/schedule/Schedule.tsx

스케줄이 없는 경우 스케줄이 없다는 문구를 추가했습니다.
캘린더 하단에 생성된 스케줄이 없습니다. 스케줄을 생성해주세요! 문구를 추가했습니다.
close #281

refactor: 스케줄이 없는 경우 스케줄이 없다는 문구추가

---

src/pages/mypage/MyPage.tsx

fix: 마이페이지 버그 수정

---

src/components/common/header/Header.tsx
src/components/common/profile/Profile.tsx
src/components/common/toast/index.tsx
src/pages/EditChildren/EditChildren.tsx
src/pages/EditChildren/EditingChildren.tsx
src/pages/home/HomePage.tsx
src/routes/index.tsx

서버단에서 넘어오는 string 객체가 똑같아서, 리랜더링이 안되는 이슈 발견하여 급하게 `reload` 이용하여 불을 꺼두었습니다.. 
현재 세영님께 img string 변경 요청 드린 상황이라, 이후 서버단 데이터가 변경되면 조금 깜빡이는 이슈가 변할 것으로 보입니다. 
close #186

[Bug] : 아이 사진 수정 정보가 바로 반영 안되는 현상 해결

---

package-lock.json
package.json
src/components/BottomSheet/Dimmer.tsx
src/components/common/label/LabelType.ts
src/components/common/scheduleBox/ScheduleBox.tsx
src/components/common/scheduleBox/ScheduleBoxType.ts
src/components/review/ReviewBottomSheet.tsx
src/libs/api/academy/AcademyType.ts
src/libs/api/dashboard/DashBoardApi.ts
src/libs/api/dashboard/DashBoardType.ts
src/libs/hooks/useOutSideClick.ts
src/pages/academy/AcademyDashboard.tsx
src/pages/academy/academyDetail/AcademyDetailClass.tsx
src/pages/academy/academyDetail/AcademyDetailHeader.tsx
src/pages/academy/academyDetail/AcademySetting.tsx
src/pages/academy/academyDetail/index.tsx
src/pages/academy/addSchedule/AddAcademyInfo.tsx
src/pages/academy/addSchedule/AddAcademyName.tsx
src/pages/academy/addSchedule/index.tsx
src/routes/index.tsx

- `split` 에러 때문에 디테일 페이지가 배포 안된 것처럼 보이는 문제 해결...
- 특정 부분이 안눌리는 부분 해결 (`e.propagation` 활용)
- 디테일한 Icon UI 개선 
- 리뷰 남기기 bottomsheet 개선
- 백엔드 스키마 변경에 따라, `라벨` 로만 보이는 과목명 수정 
- `invalidateQueries` 활용하여 학원에 대한 등록여부 바로바로 화면에 반영되게끔 수정
close #274

[Bug] : Dashboard 관련 2차 QA 수정사항 반영

---

src/components/Loading/Loading.tsx
src/components/academy/CustomTimePicker.tsx
src/components/common/button/Button.tsx
src/components/common/calender/Calender.stories.tsx
src/components/common/modal/Modal.tsx
src/components/schedule/SelectAttendanceDate.tsx
src/libs/api/children/ChildrenType.ts
src/libs/api/dashboard/DashBoardApi.ts
src/libs/api/filter/filterApi.ts
src/libs/api/index.ts
src/libs/api/mapapi/mapApi.ts
src/libs/api/onboarding.ts
src/libs/api/schedule/scheduleType.ts
src/libs/store/childInfoAtom.tsx
src/libs/store/scheduleInfo.tsx
src/libs/utils/date.ts
src/libs/utils/scheduleParse.ts
src/libs/utils/storage.ts
src/pages/EditChildren/EditChildren.tsx
src/pages/academy/AcademyDashboard.tsx
src/pages/academy/detailSchedule/DetailScheduleHeader.tsx
src/pages/academy/detailSchedule/DetailSchedulePage.tsx
src/pages/home/HomePage.tsx
src/pages/mypage/MyPage.tsx
src/pages/schedule/edit/index.tsx
src/pages/schedule/new/AddScheduleAcademy.tsx
src/pages/schedule/new/AddScheduleTime.tsx
src/pages/schedule/new/index.tsx

- `schedule`을 생성할 때, 시작일과 종료일을 선택하지 않으면 에러 발생하게끔 return 지정하기
- 일정 수정 시에는 아이 정보, 학원 정보 수정 불가능하게끔 지정하기 
- 스케쥴을 누르면 버튼이 클릭되는 현상처럼 보이는 부분 개선 
close #226

[Refac]: schedule 생성, 수정 validation 추가

---

src/components/common/profile/Profile.tsx
src/libs/api/children/ChildrenApi.ts
src/pages/EditChildren/EditChildren.tsx
src/pages/EditChildren/EditingChildren.tsx
src/pages/home/HomePage.tsx

- 프로필 이미지가 수정되면, 수정값을 바로 확인할 수 있도록 개선
- react query를 활용하여 코드 간결화
close #310

[Bug] : 프로필 이미지 수정 로직 개선

---

src/components/BottomSheet/BottomSheetContent.tsx
src/components/common/slider/Slider.tsx
src/components/map/MapBottomSheet.tsx
src/components/map/MapBottomSheetItem.tsx
src/components/map/MapSearchBar.tsx
src/components/map/NaverMap.tsx
src/components/map/ReviewGraph.tsx
src/components/map/constants.ts
src/components/map/naverMapType.ts
src/libs/api/filter/filterApi.ts
src/libs/api/filter/filterApiType.ts
src/libs/api/mapapi/mapApi.ts
src/libs/api/mapapi/mapApiType.ts
src/libs/store/mapInfoAtom.ts
src/pages/filter/FilterPage.tsx
src/pages/filter/filterType.ts
src/pages/map/MapPage.tsx
src/routes/index.tsx

맵 페이지에 페이지 네이션을 적용해서 구현하였습니다.
- 페이지 네이션 적용
- 맵 전체 UI 변경

맵 페이지 리펙토링

---

src/components/map/MapBottomSheet.tsx
src/components/map/NaverMap.tsx

fix: 맵 페이지 바텀시트 버그 수정 하였습니다.
- 바텀시트를 3댑스로 변경하였습니다.
- 학원을 선택한 상태에서는 현재 위치에서 검색을 못하도록 수정하였습니다.
- 학원을 선택한 상태에서는 GPS 버튼을 안보이게 하였습니다.

fix: 맵 페이지 바텀시트 버그 수정

---

src/components/common/button/Button.tsx
src/components/common/button/ButtonType.ts
src/pages/academy/detailSchedule/DetailScheduleHeader.tsx
src/pages/academy/detailSchedule/DetailSchedulePage.tsx
src/pages/likeAcademy/LikeAcademy.tsx
src/pages/onboarding/OnbardingPage.tsx

- schedule detail개행문제 해결했습니다.
- 온보딩 버튼 문제 해결

스케줄 detail 겹치는 문제 + 온보딩 버튼 안 보이는 문제 해결

---

src/pages/academy/detailSchedule/DetailSchedulePage.tsx

schedule detail 부분 아코디언 박스에 불필요한 border가 있어서 제거했습니다

fix: schedule detail page불필요한 border제거

---

src/components/common/badge/Badge.stories.tsx
src/components/common/badge/Badge.tsx
tailwind.config.js

Feat: Badge 컴포넌트 추가 및 컬러값 추가
